### PR TITLE
add CI via GitHub actions

### PR DESCRIPTION
**Pull request by ranocha**
This sets up CI via GitHub actions.

### CODE REVIEW

**Comment by cstjean** [comment]
Thanks! Though, is it normal that it says only "Unrolled tests passed"? Shouldn't there be a number-of-tests? Or is that the new thing in Julia 1.8?

**Comment by ranocha** [comment]
> is it normal that it says only "Unrolled tests passed"? 

That's something I added manually to the CI script. It's not the default CI script most packages use since I combine coverage reports for Coveralls manually, see line
https://github.com/cstjean/Unrolled.jl/blob/ed843290eed0cd6442cb09cfefdd45cc172eded6/.github/workflows/CI.yml#L31
and the following ones. The line
https://github.com/cstjean/Unrolled.jl/blob/ed843290eed0cd6442cb09cfefdd45cc172eded6/.github/workflows/CI.yml#L100
is just there to make it easier to debug the script when things go wrong with GitHub actions.

**Comment by ranocha** [comment]
I don't know - do you use test sets?

**Comment by cstjean** [comment]
Ah, right! Just plain tests. It's been a while since I've worked on this package 😛

**Pull request merged**
